name: gaia

on: workflow_dispatch

jobs:
  gaia:
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Set up QEMU
#        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.4.1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd gaia
          bash build.sh

      - name: Compress
        run: xz -T $(nproc) gaia/images/gaia.img
    

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: gaia
          path: gaia/images/gaia.img.xz
