name: iris

on: workflow_dispatch

jobs:
  iris:
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Set up QEMU
#        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd iris
          bash build.sh

      - name: Compress
        run: xz -T $(nproc) iris/images/iris.img
    

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: iris/images/iris.img.xz
